# Generated by Django 4.1.1 on 2022-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmf',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
